### ISSUE TITLE
Failed to send request

### ISSUE THREAD

**Issue by gefeo** [itds-consulting/android-silent-ping-sms#11]
Worked the first time i installed it, days ago, but not anymore. More exactly it sends messages, as Android warns me about flood when i click many times on the send button, but app seems doing nothing (else than add number to history) and finally i get the error message FAILED TO SEND REQUEST

Between the date it worked and now i installed multiple apps from f-android and gplay (new phone...). And also i opened ingeener menu and did nothing but increase logging verbosity (well im not sure where are the logs located at this point). But not much.

How can i get error messages from SMS Ping and help debug it?
Ty

**Comment by gefeo** [comment]
Nevermind. As a bad n00b i changed my SMSC. After i put the correct phone number in there everything is working again

**Comment by smarek** [comment]
Cool :+1:
