### ISSUE TITLE
Is this clone on Play Store illegal?

### ISSUE THREAD

**Issue by ranit8** [itds-consulting/android-silent-ping-sms#12]
https://play.google.com/store/apps/details?id=com.itds.sms.ping

**Comment by smarek** [comment]
It is unathorized, breaches GPLv3 by not publishing original sources, and I don't like it. It certainly isn't our work / account, and dressler media is using old codebase from 2016

**Comment by smichel17** [comment]
You can submit a DMCA take-down request here:  https://support.google.com/legal/contact/lr_dmca?product=googleplay
