### ISSUE TITLE
Location not getting

### ISSUE THREAD

**Issue by GewoonJaap** [itds-consulting/android-silent-ping-sms#14]
I sent the SMS ping, to someone but i dont get his location. Is this normal?

**Comment by smarek** [comment]
Yes, the application does not reveal target location, only it's online/offline status

**Comment by GewoonJaap** [comment]
Is it possible to get location?

**Comment by smarek** [comment]
not with this application

**Comment by GewoonJaap** [comment]
Is there a app that can do this?

**Comment by diirrt** [comment]
I have the same question

**Comment by smarek** [comment]
Not with any user-invokable service. Phone location is stored within HLR (or similar service), and this can be queried only via SS7/Diameter call invocation (call meaning API usage, not phone-call). This information is more-or-less protected by operator using home-filtering or SS7-interconnect firewalling/filtering/censoring.

You can get inaccurate location of phone, if you are able to intercept outgoing phone sms/call, in which case you get some info about cellular BTSs, and can approximate.

Most precise way to find out remote phone location is to send him a link to website, which will use HTML5 APIs to obtain device approximate or precise (GPS) location, but this way is usually protected in some way within common browsers.

So the answer is, as usual, there is no easy way to obtain remote phone location, without having access to SS7 services (best within phone's HPLMN), knowing of vulnerability of targeted user, or compromise user's privacy some other way.
