### ISSUE TITLE
Bug on Silent Sms Ping: Clicking On send without adding recipients causes the app to crash. 

### ISSUE THREAD

**Issue by gutzygwin** [itds-consulting/android-silent-ping-sms#18]
#### Expected behavior
Silent Sms Ping is an open source andriod application which helps secretly send a message to a receiver without notifying the user that the message has been received via notification drop box or any other means. Using Silent Sms ping as explained are to carry specific duties without obstacles. 

#### Actual behavior
Simply Opening the application and clicking send without doing anything else such as adding recipients name or going through history. Just simply clicking on send as soon as the application is opened causes the application to crash which is an error.

#### How to reproduce
* Download Silent Sms Ping from F-driod application. 
* Open the application. 
* Click on send. 
* Application Crashes. 

--------------------------------------------------------

* version of the application : **v 3**
* last updated : **12/4/17**

--------------------------------------------------------

* Browser: F-driod / Sms Ping
* Operating system: Andriod 7.0

#### Recording Of The Bug

https://youtu.be/Qcewwd_TAmA
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@gutzygwin/bug-on-silent-sms-ping-clicking-on-sending-without-adding-recipients-causes-the-app-to-crash">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by smarek** [comment]
Well, damn, why do you hit send button, when there is no recipient? That makes no sense, does it?
