### ISSUE TITLE
Suggestion for improvement

### ISSUE THREAD

**Issue by syntropic** [itds-consulting/android-silent-ping-sms#19]
If you code the DCS octet as 0xD4 as opposed to 0x04, it will reduce the possibility of the recipient being notified in any way. 

I have a rooted phone (am HTC 10) with the original android PDU library (as it is still is included in stock HTC ROMs), and when I send the message generated by your app, it works insofar as correctly indicating that a phone is offline, but for online phones, I receive a blank message (with the senders number).

0x04 (0000 0100) is an 8-bit class 0 message, and since it is 8-bit, no message displays, but at least on the phones I have tested (a Samsung S3 and an HTC One M8), a blank message is received. Since most people are not going to be able to send a true type 0 message (with the PID octet set to 0x40), an alternative is to set the DCS octet bit 6. This, according to the specs (3GPP 23.038.010 version 10), marks the message for automatic deletion. So the bit coding for DCS becomes 0100 0100 or 0xD4.

In my testing, using this change, I still receive an ACK (or delivery report) but the phone does not receive a blank message with senders number.

**Comment by smarek** [comment]
Hey @syntropic, cool analysis, however, since we don't support and don't require root permissions, we cannot control the DCS field, but prove me wrong if you know more.

From what I know, call stack is
```
#1 android.telephony.SmsManager.sendDataMessage(String destinationAddress, String scAddress, short destinationPort, byte[] data, PendingIntent sentIntent, PendingIntent deliveryIntent)
#2 com.android.internal.telephony.UiccSmsController.sendDataForSubscriber(int subId, String callingPackage, String destAddr, String scAddr, int destPort, byte[] data, PendingIntent sentIntent, PendingIntent deliveryIntent)
#3 com.android.internal.telephony.IccSmsInterfaceManager.sendData(String callingPackage, String destAddr, String scAddr, int destPort, byte[] data, PendingIntent sentIntent, PendingIntent deliveryIntent)
#4 com.android.internal.telephony.IccSmsInterfaceManager.sendDataInternal(String callingPackage, String destAddr, String scAddr, int destPort, byte[] data, PendingIntent sentIntent, PendingIntent deliveryIntent)
#5 com.android.internal.telephony.sendData(String destAddr, String scAddr, int destPort, byte[] data, PendingIntent sentIntent, PendingIntent deliveryIntent);
# abstract method implemented by either
# com/android/internal/telephony/cdma/CdmaSMSDispatcher.java
# com/android/internal/telephony/gsm/GsmSMSDispatcher.java
# in either case, SmsManager.getSubmitPdu is called in respective package (gsm or cdma)
# 6gsm com.android.internal.telephony.gsm.SmsMessage.getSubmitPdu(String scAddress, String destinationAddress, int destinationPort, byte[] data, boolean statusReportRequested)
# GSM: https://github.com/aosp-mirror/platform_frameworks_base/blob/master/telephony/java/com/android/internal/telephony/gsm/SmsMessage.java#L509
# 6cdma com.android.internal.telephony.cdma.SmsMessage.getSubmitPdu(String scAddr, String destAddr, int destPort, byte[] data, boolean statusReportRequested)
# CDMA: https://github.com/aosp-mirror/platform_frameworks_base/blob/master/telephony/java/com/android/internal/telephony/cdma/SmsMessage.java#L271
```

Because we're talking GSM here, we're interested in https://github.com/aosp-mirror/platform_frameworks_base/blob/master/telephony/java/com/android/internal/telephony/gsm/SmsMessage.java#L540 where TP-DCS is statically assigned 0x04 value, and I don't really see any way to influence that
