### ISSUE TITLE
Logo proposal for Silent Ping Sms

### ISSUE THREAD

**Issue by baranpirincal** [itds-consulting/android-silent-ping-sms#20]
Hello, I wanted to design a logo for Silent Ping Sms. I hope you like it!

![hadi2](https://user-images.githubusercontent.com/37786733/38467872-bbea9d82-3b46-11e8-8352-b89f7dc5c23a.jpg)

**Comment by smarek** [comment]
Hello, thank you! Can you explain what these colors mean, or if it is just pallete to choose from? Also please provide one or all of them in PNG with transparent background, then we will be able to integrate to Android environment. :+1:

**Comment by baranpirincal** [comment]
Hi again. I made it just a color palette for you to choose. In my opinion 
it may be good to use a dark color like gray or black because of the function of application ("silent")


![editable files](https://user-images.githubusercontent.com/37786733/38873363-41c12d18-425e-11e8-8087-57b8900b6bc4.jpg)
