### ISSUE TITLE
Cancel the silent?

### ISSUE THREAD

**Issue by justanidea** [itds-consulting/android-silent-ping-sms#21]
Hey guys, i tried the app and now my friend doesnt receive my sms at all, how can I cancel that?

**Comment by smarek** [comment]
Device? Anyway it should be solveable by operator, just call them.

**Comment by justanidea** [comment]
Sm g531-f  (android 5.1.1) to sm A520F (android 7.0)

thx for your answer

**Comment by smarek** [comment]
This seems like an issue with operator, did you check with them? Also what messaging/sms app does the recipient use?

**Comment by justanidea** [comment]
Finally - its quite strange - everything came normal after one week 0_o

**Comment by smarek** [comment]
I assume the message did time-outed in the network and has been thrown away by either SMSC or the phone itself, so it no longer blocks the message queue between you two. If you ever get to know what exactly happened, I'll be glad to hear from you.

Cheers!
