### ISSUE TITLE
Apk is fake

### ISSUE THREAD

**Issue by pethkaqeni** [itds-consulting/android-silent-ping-sms#3]
I have tested with a number that i know 100000℅ that is closed by operator, and the results was, sms send ok, phone is online

**Comment by smarek** [comment]
Hi, if operator provides a delivery success report for sent sms, it is considered online. We have no other means of checking if the information is correct.

**Comment by Chewie9999** [comment]
It worked for me between 2 different operators in the UK!
Thanks for the app :)

**Comment by david-sebaoun** [comment]
Works perfectly for me.
Tested on 3 different phones with 3 diffetent operators.
Thanks for your work

**Comment by tmeers91** [comment]
Does this application only work for mobile operators in the United Kingdom?

**Comment by smarek** [comment]
@tmeers91 no, we've tested with other operators Germany, Czech, Slovak, and it works here too

**Comment by tmeers91** [comment]
In North America it does not appear to be functioning (specifically for +1 country codes). It may very well be operating properly in the United Kingdom and European countries, I am just indicating my observations.

**Comment by smarek** [comment]
@tmeers91 did not test it there, i presume for standard sms you can get delivery report, can you verify that there is any kind of callback ? I could probably provide debug apk for that case, if you're not able to figure that out from logcat

**Comment by tmeers91** [comment]
It's fine, I was merely curious. But Thank you for your help. I ran into some confusion. So, it's all good.

**Comment by smarek** [comment]
Thank you all
