### ISSUE TITLE
Contacts list

### ISSUE THREAD

**Issue by mtbu** [itds-consulting/android-silent-ping-sms#7]
Would it be possible to have a contacts list in this app, so you can quickly ping a contact's phone, or to send one from the contacts app?

**Comment by smarek** [comment]
@mtbu that would certainly be possible, or maybe just a history of tested sms numbers would be enough for you?

**Comment by mtbu** [comment]
Either would be useful I think

**Comment by smarek** [comment]
This is available in version v2 (versionCode 3), along with picking from contact list and cleaning the history (via menu actions)
